name: Build Minimap Mod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Set up Gradle 8.5
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: 8.5

    - name: Grant execute permission for Gradle wrapper
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build
